pull_request_rules:
  - name: skipped-counts-as-success
    conditions:
      - base=main
      - "check-success = zz-required"
    actions:
      comment:
        message: "ZZ-SKIPPED-SATISFIED-CHECK-SUCCESS"
  - name: observe-skipped
    conditions:
      - base=main
      - "check-skipped = zz-required"
    actions:
      comment:
        message: "ZZ-OBSERVED-SKIPPED"
